// File: VhdlRomGen.v
// Generated by MyHDL 0.11
// Date: Fri Jul  2 21:29:25 2021


`timescale 1ns/10ps

module VhdlRomGen (
    addr,
    data
);


input [3:0] addr;
output [7:0] data;
reg [7:0] data;




always @(addr) begin: VHDLROMGEN_RTL_ROM
    case (addr)
        0: data = 0;
        1: data = 1;
        2: data = 2;
        3: data = 3;
        4: data = 4;
        5: data = 5;
        6: data = 6;
        7: data = 7;
        8: data = 8;
        9: data = 9;
        10: data = 10;
        11: data = 11;
        12: data = 12;
        13: data = 13;
        14: data = 14;
        default: data = 15;
    endcase
end

endmodule
